### ISSUE TITLE
ssltun support CONNECT method ?

### ISSUE THREAD

**Issue by ingnelson** [taoso/led#1]
Hello.

My name is Nelson, I am from Nicaragua, can you help me with a reverse proxy , i would be glad to pay you for your services.

1) I am behind a firewall

 2) The client is a Android Application, it can sends an HTTP request with the proxy and then to the SSH server to create the tunnel

3) On the internet I found the following:
 HTTP proxy: 50.18.211.227:8043
 Fully qualified domain name (FQDN): 5ef50094901b6f5fccdfd0f6-172-245-22-211.cloudmi.datami.net

The proxy is linked to their domain, the only thing that altered was the domain which removed their IP that it had and put or added mine 172-245-22-211 so that your proxy will not reject the connection.

I show you the connection that WIRESHARK shows me. What you send and what you receive :

![Tunnel1](https://user-images.githubusercontent.com/6626845/86406195-e950cd80-bc6f-11ea-831e-9354405d4ccf.jpg)
![Tunnel2](https://user-images.githubusercontent.com/6626845/86406203-eb1a9100-bc6f-11ea-9db5-0d6d7c572f97.jpg)

It is possible to create a proxy that support CONNECT method and support HTTPS or SSL  like that proxy I found on the internet  ? 

The proxy 50.18.211.227:8043  response is :

HTTP/1.1 200 Connection established.
Server: sdgw

then goes the response from my SSH dropbear and the tunnel is created.

i want a proxy like that on my VPS using my domain datami.ssl.zteclaro.tk

**Comment by taoso** [comment]
> It is possible to create a proxy that support CONNECT method and support HTTPS or SSL like that proxy I found on the internet ?

Yes. However, ssltun current only support security http proxy, which means that client should send connect over HTTPS connection, which is not supported widely.

If you need a plaintext http tunnel server, just make small modification to the source code is enough.

**Comment by ingnelson** [comment]
@lvht if I give you my VPS IP , my user and password could you create that kind of proxy on some listen port ? , this would help me a lot ! 

I am glad to pay you via PAYPAL  or BITCOIN

Tell me what way I can send you my VPS .

I will wait your answer.

**Comment by lvht** [comment]
you could send email to me. my email is ihaitao#qq.com(replace # with @)
